/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Boundry.LRep;

import Boundary.Agent.*;
import Boundary.Main.iWindow;
import Controller.Agent.ManageController;
import Controller.Main.iMuzaMusic;
import Entity.Artist;
import Entity.EArtistStatus;
import Entity.Location;
import Entity.OpenLocation;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JSpinner;

/**
 *
 * @author Administrator
 */
public class frmEditLocation extends javax.swing.JInternalFrame {
    Location loc = null;
    
    /**
     * Creates new form frmNewArtist
     */
    public frmEditLocation() {
        setTitle("Location Editor");
        initComponents();
        loc = Controller.LRep.LocationManager.getLocation();
        if(loc!=null){
        lblID.setText(loc.getLocationID());
        lblGreeting.setText("Dear "+iMuzaMusic.getLoggedUser().getFirstName()+", please use the form below to edit your location details.");
        
        if(loc!=null)
            refreshData();
        }else lblGreeting.setText("Dear "+iMuzaMusic.getLoggedUser().getFirstName()+", please use the form below to create your location details.");
        
        lblID.setText(Controller.LRep.LocationManager.getNextIndex());
        
    }
    
    public void refreshData(){
        isOpenLocation.setEnabled(false);
        fldEmailAddr.setText(loc.getStrAddress());
        fldEmail.setText(loc.getStrEmail());
        fldGoogleMap.setText(loc.getUrlGoogleMaps());
        fldPhone.setText(loc.getiPhoneNum());
        fldStageName.setText(loc.getStrName());
        spnCapacity.setModel(new javax.swing.SpinnerNumberModel((int)loc.getMaxCapacity(), 1, null, 1));
        if(loc instanceof OpenLocation){
            isOpenLocation.setSelected(true);
            pnlOpenLocation.setVisible(true);
            OpenLocation op = (OpenLocation) loc;
            slctStage.setSelectedItem(op.getStageTop());
            isAmp.setSelected(op.getIsExistingAmp());
            isLifted.setSelected(op.getIsStageLifted());
            isSits.setSelected(op.getIsExistingSits());
            isToilets.setSelected(op.getIsExistingToilets());
            
        }
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdd = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblStudioID = new javax.swing.JLabel();
        lblStudioName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblAddr = new javax.swing.JLabel();
        lblMailError = new javax.swing.JLabel();
        fldStageName = new javax.swing.JTextField();
        fldEmailAddr = new javax.swing.JTextField();
        lblAddrError = new javax.swing.JLabel();
        lblNameError = new javax.swing.JLabel();
        fldGoogleMap = new javax.swing.JTextField();
        lblErrEmail = new javax.swing.JLabel();
        errEmail = new javax.swing.JLabel();
        stStage = new javax.swing.JLabel();
        stEmail = new javax.swing.JLabel();
        stFB = new javax.swing.JLabel();
        lblAddr1 = new javax.swing.JLabel();
        fldEmail = new javax.swing.JTextField();
        stFB1 = new javax.swing.JLabel();
        lblAddrError1 = new javax.swing.JLabel();
        lblAddr2 = new javax.swing.JLabel();
        fldPhone = new javax.swing.JTextField();
        errPhone = new javax.swing.JLabel();
        lblErrPhone = new javax.swing.JLabel();
        lblAddr3 = new javax.swing.JLabel();
        spnCapacity = new javax.swing.JSpinner();
        pnlOpenLocation = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        slctStage = new javax.swing.JComboBox<>();
        isToilets = new javax.swing.JCheckBox();
        isSits = new javax.swing.JCheckBox();
        isLifted = new javax.swing.JCheckBox();
        isAmp = new javax.swing.JCheckBox();
        isOpenLocation = new javax.swing.JCheckBox();
        vIcon = new javax.swing.JLabel();
        xIcon = new javax.swing.JLabel();
        lblGreeting = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        errSubmit = new javax.swing.JLabel();
        lblSubmit = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        pnlAdd.setBackground(new Color(255,255,255,60));
        pnlAdd.setOpaque(false);
        pnlAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("Studio ID");
        pnlAdd.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 170, -1));

        lblStudioID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStudioID.setForeground(new java.awt.Color(255, 255, 255));
        lblStudioID.setText("Location ID");
        pnlAdd.add(lblStudioID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        lblStudioName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStudioName.setForeground(new java.awt.Color(255, 255, 255));
        lblStudioName.setText("Location Name");
        pnlAdd.add(lblStudioName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, 20));

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Contact Email");
        pnlAdd.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, -1));

        lblAddr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAddr.setForeground(new java.awt.Color(255, 255, 255));
        lblAddr.setText("Location Google Maps URL");
        pnlAdd.add(lblAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 300, -1));

        lblMailError.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblMailError.setForeground(new java.awt.Color(255, 0, 51));
        pnlAdd.add(lblMailError, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 360, 20));

        fldStageName.setText("Enter Stage Name");
        fldStageName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fldStageNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fldStageNameFocusLost(evt);
            }
        });
        fldStageName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldStageNameActionPerformed(evt);
            }
        });
        pnlAdd.add(fldStageName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 190, -1));

        fldEmailAddr.setText("Enter Email Address");
        fldEmailAddr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fldEmailAddrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fldEmailAddrFocusLost(evt);
            }
        });
        pnlAdd.add(fldEmailAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 190, -1));

        lblAddrError.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblAddrError.setForeground(new java.awt.Color(255, 0, 51));
        pnlAdd.add(lblAddrError, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 370, 20));

        lblNameError.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblNameError.setForeground(new java.awt.Color(255, 0, 51));
        pnlAdd.add(lblNameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 360, 20));

        fldGoogleMap.setText("Google Map URL");
        fldGoogleMap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fldGoogleMapFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fldGoogleMapFocusLost(evt);
            }
        });
        pnlAdd.add(fldGoogleMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 190, -1));

        lblErrEmail.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblErrEmail.setForeground(new java.awt.Color(255, 0, 51));
        pnlAdd.add(lblErrEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 370, 20));
        pnlAdd.add(errEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 40, 20));
        pnlAdd.add(stStage, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 50, 20));
        pnlAdd.add(stEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 40, 20));
        pnlAdd.add(stFB, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 40, 20));

        lblAddr1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAddr1.setForeground(new java.awt.Color(255, 255, 255));
        lblAddr1.setText("Location Address");
        pnlAdd.add(lblAddr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 300, -1));

        fldEmail.setText("Enter Location Address");
        fldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fldEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fldEmailFocusLost(evt);
            }
        });
        pnlAdd.add(fldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 190, -1));
        pnlAdd.add(stFB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 40, 20));

        lblAddrError1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblAddrError1.setForeground(new java.awt.Color(255, 0, 51));
        pnlAdd.add(lblAddrError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 370, 20));

        lblAddr2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAddr2.setForeground(new java.awt.Color(255, 255, 255));
        lblAddr2.setText("Phone Number");
        pnlAdd.add(lblAddr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 300, -1));

        fldPhone.setText("Enter Phone Number");
        fldPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fldPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fldPhoneFocusLost(evt);
            }
        });
        pnlAdd.add(fldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 190, -1));
        pnlAdd.add(errPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 40, 20));

        lblErrPhone.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblErrPhone.setForeground(new java.awt.Color(255, 0, 51));
        pnlAdd.add(lblErrPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 370, 20));

        lblAddr3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAddr3.setForeground(new java.awt.Color(255, 255, 255));
        lblAddr3.setText("Max Capacity");
        pnlAdd.add(lblAddr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 180, -1));

        spnCapacity.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        pnlAdd.add(spnCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 50, -1));

        pnlOpenLocation.setBackground(new Color(0,0,0,0));
        pnlOpenLocation.setVisible(false);
        pnlOpenLocation.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlOpenLocationMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlOpenLocationMouseMoved(evt);
            }
        });
        pnlOpenLocation.setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Open Location Details");
        pnlOpenLocation.add(jLabel2);
        jLabel2.setBounds(190, 0, 220, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Stage Type");
        pnlOpenLocation.add(jLabel3);
        jLabel3.setBounds(10, 30, 110, 20);

        slctStage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Partial", "Full" }));
        pnlOpenLocation.add(slctStage);
        slctStage.setBounds(190, 30, 100, 22);

        isToilets.setBackground(new java.awt.Color(0, 0, 0));
        isToilets.setForeground(new java.awt.Color(255, 255, 255));
        isToilets.setText("Existing Toilets");
        isToilets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isToiletsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isToiletsMouseExited(evt);
            }
        });
        isToilets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isToiletsActionPerformed(evt);
            }
        });
        pnlOpenLocation.add(isToilets);
        isToilets.setBounds(10, 150, 160, 25);

        isSits.setBackground(new java.awt.Color(0, 0, 0));
        isSits.setForeground(new java.awt.Color(255, 255, 255));
        isSits.setText("Existing Sits");
        isSits.setFocusPainted(false);
        isSits.setFocusable(false);
        isSits.setRequestFocusEnabled(false);
        isSits.setRolloverEnabled(false);
        isSits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isSitsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isSitsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                isSitsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                isSitsMouseReleased(evt);
            }
        });
        isSits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isSitsActionPerformed(evt);
            }
        });
        pnlOpenLocation.add(isSits);
        isSits.setBounds(10, 60, 160, 24);

        isLifted.setBackground(new java.awt.Color(0, 0, 0));
        isLifted.setForeground(new java.awt.Color(255, 255, 255));
        isLifted.setText("Stage Lifted");
        isLifted.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isLiftedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isLiftedMouseExited(evt);
            }
        });
        isLifted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isLiftedActionPerformed(evt);
            }
        });
        pnlOpenLocation.add(isLifted);
        isLifted.setBounds(10, 90, 160, 25);

        isAmp.setBackground(new java.awt.Color(0, 0, 0));
        isAmp.setForeground(new java.awt.Color(255, 255, 255));
        isAmp.setLabel("Existing Amplifier");
        isAmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isAmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isAmpMouseExited(evt);
            }
        });
        isAmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isAmpActionPerformed(evt);
            }
        });
        pnlOpenLocation.add(isAmp);
        isAmp.setBounds(10, 120, 160, 25);

        pnlAdd.add(pnlOpenLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 550, 180));

        isOpenLocation.setBackground(new java.awt.Color(0, 0, 0));
        isOpenLocation.setForeground(new java.awt.Color(255, 255, 255));
        isOpenLocation.setText("Open Location");
        isOpenLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isOpenLocationActionPerformed(evt);
            }
        });
        pnlAdd.add(isOpenLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 150, -1));

        getContentPane().add(pnlAdd);
        pnlAdd.setBounds(10, 40, 780, 460);

        vIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/Images/v.png"))); // NOI18N
        vIcon.setVisible(false);
        getContentPane().add(vIcon);
        vIcon.setBounds(750, 340, 48, 16);

        xIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/Images/x.png"))); // NOI18N
        xIcon.setVisible(false);
        getContentPane().add(xIcon);
        xIcon.setBounds(750, 320, 16, 16);

        lblGreeting.setForeground(new java.awt.Color(255, 255, 255));
        lblGreeting.setText("greetingtext");
        getContentPane().add(lblGreeting);
        lblGreeting.setBounds(20, 10, 700, 16);

        jButton2.setText("Update Location");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 520, 170, 25);
        getContentPane().add(errSubmit);
        errSubmit.setBounds(200, 520, 40, 30);

        lblSubmit.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblSubmit);
        lblSubmit.setBounds(250, 520, 290, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fldStageNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fldStageNameFocusGained
        if (fldStageName.getText().equals("Enter Stage Name"))
        fldStageName.setText("");
    }//GEN-LAST:event_fldStageNameFocusGained

    private void fldStageNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fldStageNameFocusLost
        String sn = fldStageName.getText();
        if (sn.length() < 3)
            lblNameError.setText("Name is too short");
        else  if (!Controller.Validators.CharValidator.isWord(sn))
            lblNameError.setText("Name must contain at least 3 valid letters");
        else lblNameError.setText("");
        
        if(lblNameError.getText().equals("")) //no error
            stStage.setIcon(vIcon.getIcon());
        else stStage.setIcon(xIcon.getIcon());
        
        iWindow.update();
        
        
    }//GEN-LAST:event_fldStageNameFocusLost

    private void fldEmailAddrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fldEmailAddrFocusGained
        if (fldEmailAddr.getText().equals("Enter Email"))
        fldEmailAddr.setText("");
    }//GEN-LAST:event_fldEmailAddrFocusGained

    private void fldEmailAddrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fldEmailAddrFocusLost
        String mail = fldEmailAddr.getText();
        if (!Controller.Validators.EmailValidator.validateEmail(mail))
            lblMailError.setText("Please enter valid email - username@domain.host");
         else lblMailError.setText("");

        if(lblMailError.getText().equals("")) //no error
            stEmail.setIcon(vIcon.getIcon());
        else stEmail.setIcon(xIcon.getIcon());
        iWindow.update();

    }//GEN-LAST:event_fldEmailAddrFocusLost

    private void fldGoogleMapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fldGoogleMapFocusGained
        if (fldGoogleMap.getText().equals("Facebook Profile URL"))
        fldGoogleMap.setText("");
    }//GEN-LAST:event_fldGoogleMapFocusGained

    private void fldGoogleMapFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fldGoogleMapFocusLost
        String sn = fldGoogleMap.getText();
        if(!sn.contains("http://") || !sn.contains("google"))
            lblAddrError.setText("URL is Invalid.");
        else if (sn.length() < 5)
            lblAddrError.setText("Address is too short");
        else lblAddrError.setText("");
        
        if(lblAddrError.getText().equals("")) //no error
            stFB.setIcon(vIcon.getIcon());
        else stFB.setIcon(xIcon.getIcon());
        
        iWindow.update();
    }//GEN-LAST:event_fldGoogleMapFocusLost

    private void fldStageNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldStageNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldStageNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Attempt to add an artist
        if(lblNameError.getText().length()>0 || lblMailError.getText().length()>0 || lblAddrError.getText().length()>0 || lblErrEmail.getText().length()>0){
            errSubmit.setIcon(xIcon.getIcon());
            lblSubmit.setText("Please fill all the fields before submitting.");
            
        
            iWindow.update();
            return;
        }
        errSubmit.setIcon(null);
        lblSubmit.setText("");
        
      //  Artist a = new Artist(lblID.getText(), jTextArea1.getText(), fldStageName.getText(), fldGoogleMap.getText() ,EArtistStatus.Active, fldAddress.getText(), this.iconPath);
        //ManageController.createArtist(a);
        iMuzaMusic.Success("You have successfully edited location "+fldStageName.getText()+".");
        iWindow.update();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fldEmailFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_fldEmailFocusGained

    private void fldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fldEmailFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fldEmailFocusLost

    private void fldPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fldPhoneFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_fldPhoneFocusGained

    private void fldPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fldPhoneFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fldPhoneFocusLost

    private void isToiletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isToiletsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isToiletsActionPerformed

    private void isSitsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isSitsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_isSitsMouseEntered

    private void isSitsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isSitsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_isSitsMouseExited

    private void isLiftedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isLiftedMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_isLiftedMouseEntered

    private void isLiftedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isLiftedMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_isLiftedMouseExited

    private void isAmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isAmpMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_isAmpMouseEntered

    private void isAmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isAmpMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_isAmpMouseExited

    private void isToiletsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isToiletsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_isToiletsMouseEntered

    private void isToiletsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isToiletsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_isToiletsMouseExited

    private void isAmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isAmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isAmpActionPerformed

    private void isLiftedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isLiftedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isLiftedActionPerformed

    private void isSitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isSitsActionPerformed
        // TODO add your handling code here:
        iWindow.update();
    }//GEN-LAST:event_isSitsActionPerformed

    private void isSitsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isSitsMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_isSitsMousePressed

    private void isSitsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isSitsMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_isSitsMouseReleased

    private void pnlOpenLocationMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlOpenLocationMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlOpenLocationMouseDragged

    private void pnlOpenLocationMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlOpenLocationMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlOpenLocationMouseMoved

    private void isOpenLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isOpenLocationActionPerformed
        // TODO add your handling code here:
        if(isOpenLocation.isSelected())
            pnlOpenLocation.setVisible(true);
        else pnlOpenLocation.setVisible(false);
        iWindow.update();
    }//GEN-LAST:event_isOpenLocationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errEmail;
    private javax.swing.JLabel errPhone;
    private javax.swing.JLabel errSubmit;
    private javax.swing.JTextField fldEmail;
    private javax.swing.JTextField fldEmailAddr;
    private javax.swing.JTextField fldGoogleMap;
    private javax.swing.JTextField fldPhone;
    private javax.swing.JTextField fldStageName;
    private javax.swing.JCheckBox isAmp;
    private javax.swing.JCheckBox isLifted;
    private javax.swing.JCheckBox isOpenLocation;
    private javax.swing.JCheckBox isSits;
    private javax.swing.JCheckBox isToilets;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAddr;
    private javax.swing.JLabel lblAddr1;
    private javax.swing.JLabel lblAddr2;
    private javax.swing.JLabel lblAddr3;
    private javax.swing.JLabel lblAddrError;
    private javax.swing.JLabel lblAddrError1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblErrEmail;
    private javax.swing.JLabel lblErrPhone;
    private javax.swing.JLabel lblGreeting;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMailError;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblStudioID;
    private javax.swing.JLabel lblStudioName;
    private javax.swing.JLabel lblSubmit;
    private javax.swing.JPanel pnlAdd;
    private javax.swing.JPanel pnlOpenLocation;
    private javax.swing.JComboBox<String> slctStage;
    private javax.swing.JSpinner spnCapacity;
    private javax.swing.JLabel stEmail;
    private javax.swing.JLabel stFB;
    private javax.swing.JLabel stFB1;
    private javax.swing.JLabel stStage;
    private javax.swing.JLabel vIcon;
    private javax.swing.JLabel xIcon;
    // End of variables declaration//GEN-END:variables
}
