/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Boundary.General;

/**
 *
 * @author nisan
 */
public class frmSuccess extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmSuccess
     */
    public frmSuccess(String success) {
        initComponents();
        lblDesc.setText(success);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/Images/success-icon.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 200, 270, 270);

        lblDesc.setForeground(new java.awt.Color(255, 255, 255));
        lblDesc.setText("jLabel2");
        getContentPane().add(lblDesc);
        lblDesc.setBounds(30, 90, 810, 16);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thank you!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 40, 160, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDesc;
    // End of variables declaration//GEN-END:variables
}
