/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Boundary.General;

import Boundary.Main.LoginGui;
import Controller.Main.LoginController;
import Controller.Main.iMuzaMusic;
import Entity.Person;
import java.awt.Color;
import java.awt.Container;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author nisan
 */
public class LoginWindow extends javax.swing.JFrame {
    /**
     * Creates new form LoginWindow
     */
    public LoginWindow() {
        iMuzaMusic.setDebug(this);
        Container c = this.getContentPane();
        c.setBackground(Color.black);
        setBackground(Color.black);

        List<Person> pList = new ArrayList<Person>();
        
        pList = Controller.Main.LoginController.getPersons();
        initComponents();
        DefaultCaret caret = (DefaultCaret) txtDebug.getCaret();
        caret.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
        
        
        
        
        slctPerson.removeAllItems();
        for(Person p : pList){
            slctPerson.addItem(p);
        }
        
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtDebug = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        slctPerson = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(652, 480));
        setMinimumSize(new java.awt.Dimension(652, 480));
        setPreferredSize(new java.awt.Dimension(652, 480));
        getContentPane().setLayout(null);

        txtDebug.setBackground(new java.awt.Color(0, 0, 0));
        txtDebug.setColumns(20);
        txtDebug.setForeground(new java.awt.Color(255, 255, 255));
        txtDebug.setRows(5);
        txtDebug.setWrapStyleWord(true);
        txtDebug.setBorder(null);
        jScrollPane1.setViewportView(txtDebug);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 240, 607, 153);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Debug Log Viewer");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 210, 104, 16);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Debug Window");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 30, 420, 60);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quick Login");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 100, 80, 16);

        slctPerson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        slctPerson.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                slctPersonItemStateChanged(evt);
            }
        });
        getContentPane().add(slctPerson);
        slctPerson.setBounds(130, 100, 300, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slctPersonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_slctPersonItemStateChanged
        // TODO add your handling code here:
        Person p = (Person) slctPerson.getSelectedItem();
        if(p==null || p.getID().equals("0000"))
            return;
        
        iMuzaMusic.log("Selected Debug Quick Login Feature for "+p.getFirstName());
        iMuzaMusic.log("Logging in...");
        LoginController.logIN(p.getID(), p.getPassword());
        dispose();
        
    }//GEN-LAST:event_slctPersonItemStateChanged

   

    public void addDebug(String line){
        txtDebug.setText(line+System.getProperty("line.separator")+txtDebug.getText());
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Object> slctPerson;
    private javax.swing.JTextArea txtDebug;
    // End of variables declaration//GEN-END:variables
}
