/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Boundry.Customer;


import Boundary.Agent.*;
import Boundary.Main.iWindow;
import Controller.Agent.LocationsController;
import Controller.Customer.FanController;
import Controller.Main.iMuzaMusic;
import Entity.Artist;
import Entity.Location;
import Entity.OpenLocation;
import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Graphics;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author nisan
 */
public class frmFanArtist extends javax.swing.JInternalFrame {
    Artist formArtist = null;
    /**
     * Creates new form frmLocationManager
     */
    public frmFanArtist() {
        setTitle("Fan Your Artist!");
        initComponents();
        FanController.updateFormData(slctArtist, jTable1);
         jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent event) {
                    // do some actions here, for example
                    // print first column value from selected row
                    try{
                        System.out.println(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
                        formArtist = (Artist) jTable1.getValueAt(jTable1.getSelectedRow(), 1);
                        
                        updateData();
                    }
                    catch(Exception e){
                        
                    }
                }
            });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        slctArtist = new javax.swing.JComboBox<>();
        btnFavorite = new javax.swing.JButton();
        pnlLocationDetails = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblBio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            @Override
            public Class getColumnClass(int column) {
                switch (column) {
                    case 0:
                    return String.class;
                    case 1:
                    return String.class;
                    case 2:
                    return String.class;
                    case 3:
                    return String.class;
                    default:
                    return Boolean.class;
                }
            }
        };
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        vIcon = new javax.swing.JLabel();
        xIcon = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to Fan Your Artist area");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(43, 25, 340, 20);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Please use the below form to fan new artists, or unfan artists you already fan.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(43, 48, 574, 16);

        slctArtist.setModel(new javax.swing.DefaultComboBoxModel<>());
        slctArtist.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                slctArtistItemStateChanged(evt);
            }
        });
        getContentPane().add(slctArtist);
        slctArtist.setBounds(40, 100, 200, 22);

        btnFavorite.setText("Fan");
        btnFavorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoriteActionPerformed(evt);
            }
        });
        getContentPane().add(btnFavorite);
        btnFavorite.setBounds(260, 95, 120, 30);

        pnlLocationDetails.setVisible(false);
        pnlLocationDetails.setOpaque(false);
        pnlLocationDetails.setLayout(null);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Artist:");
        pnlLocationDetails.add(jLabel4);
        jLabel4.setBounds(10, 10, 110, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Artist Email:");
        pnlLocationDetails.add(jLabel5);
        jLabel5.setBounds(10, 30, 110, 16);

        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("jLabel5");
        pnlLocationDetails.add(lblName);
        lblName.setBounds(160, 10, 220, 20);

        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText("jLabel5");
        pnlLocationDetails.add(lblAddress);
        lblAddress.setBounds(160, 30, 260, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/Images/Facebook-Download-PNG.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
        });
        pnlLocationDetails.add(jLabel8);
        jLabel8.setBounds(440, 30, 40, 40);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Launch Facebook Profile");
        pnlLocationDetails.add(jLabel16);
        jLabel16.setBounds(390, 10, 180, 20);

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Artist Biography:");
        pnlLocationDetails.add(jLabel17);
        jLabel17.setBounds(10, 50, 130, 16);

        lblBio.setForeground(new java.awt.Color(255, 255, 255));
        lblBio.setText("jLabel3");
        pnlLocationDetails.add(lblBio);
        lblBio.setBounds(10, 70, 530, 16);

        getContentPane().add(pnlLocationDetails);
        pnlLocationDetails.setBounds(40, 130, 560, 260);

        jTable1.setBackground(new Color(0,0,0,0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 400, 510, 160);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Your favorited places");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 380, 210, 16);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("[Apply Changes]");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jLabel9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel9KeyReleased(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(470, 380, 120, 20);

        vIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/Images/v.png"))); // NOI18N
        vIcon.setVisible(false);
        getContentPane().add(vIcon);
        vIcon.setBounds(750, 340, 48, 16);

        xIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/Images/x.png"))); // NOI18N
        xIcon.setVisible(false);
        getContentPane().add(xIcon);
        xIcon.setBounds(750, 320, 16, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        iMuzaMusic.OpenURI(formArtist.getFbAddr());
    }//GEN-LAST:event_jLabel8MouseClicked

    private void slctArtistItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_slctArtistItemStateChanged
        // TODO add your handling code here:
        Artist art = (Artist) slctArtist.getSelectedItem();
        if(art==null || art.equals(new Artist("0000"))){
            pnlLocationDetails.setVisible(false);
            formArtist = null;
            return;
        }
        formArtist = art;
        updateData();
    }//GEN-LAST:event_slctArtistItemStateChanged

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        for(int i=0; i<jTable1.getRowCount(); i++){
            String ArtistID = (String) jTable1.getValueAt(i, 0);
            Boolean status = (Boolean) jTable1.getValueAt(i, 2);


            if(status){
                FanController.unFav(ArtistID);
                
                iMuzaMusic.log("Cancel favorited Artist: ArtistID: "+ArtistID);

            }

        }
        FanController.updateFormData(slctArtist, jTable1);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel9KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9KeyReleased

    private void btnFavoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoriteActionPerformed
        if(formArtist!=null && !slctArtist.getSelectedItem().equals(new Artist("0000"))){
        FanController.addFav(formArtist.getID());
        FanController.updateFormData(slctArtist, jTable1);
        }
        
        
        
    }//GEN-LAST:event_btnFavoriteActionPerformed

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseEntered

    public void updateData(){
        pnlLocationDetails.setVisible(true);
        lblName.setText(formArtist.getStageName());
        lblAddress.setText(formArtist.getEmailAddr());
        lblBio.setText(formArtist.getBiography());
        
        
        iWindow.update();
    }
        
    public Icon getIcon(Boolean status){
        if(status)
            return vIcon.getIcon();
        return xIcon.getIcon();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFavorite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBio;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel pnlLocationDetails;
    private javax.swing.JComboBox<Entity.Artist> slctArtist;
    private javax.swing.JLabel vIcon;
    private javax.swing.JLabel xIcon;
    // End of variables declaration//GEN-END:variables
}
