/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Boundry.Customer;

import Boundary.General.frmViewShows;
import Boundary.Main.iWindow;
import Controller.Agent.EvaluationsController;
import Controller.General.ViewShowController;
import Controller.Main.iMuzaMusic;
import Entity.Artist;
import Entity.Customer;
import Entity.Show;
import java.awt.Color;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JList;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.text.DefaultFormatter;

/**
 *
 * @author nisan
 */
public class frmTicketPurchase extends javax.swing.JFrame {
    Show show = null;
    frmViewShows frm = null;
    /**
     * Creates new form NewJFrame
     */
    public frmTicketPurchase(frmViewShows frm, Show show) {
        this.show = show;
        this.frm = frm;
        setUndecorated(true);
        setLocationRelativeTo(null);
        initComponents();
        lblShowDetail1.setText("Tickets purchase for "+show.getiMainArtist()+" Performence on "+(new SimpleDateFormat("dd/M/Y hh:mm")).format(show.getpStartDate()));
        lblShowDetail3.setText("Ticket price: $"+show.getpTicketPrice()+"ea");
        lblTotalPrice.setText("$"+Integer.parseInt(jSpinner1.getValue().toString())*show.getpTicketPrice());
        
        
        JComponent comp = jSpinner1.getEditor();
    JFormattedTextField field = (JFormattedTextField) comp.getComponent(0);
    DefaultFormatter formatter = (DefaultFormatter) field.getFormatter();
    formatter.setCommitsOnValidEdit(true);
    jSpinner1.addChangeListener(new ChangeListener() {

        @Override
        public void stateChanged(ChangeEvent e) {
           lblTotalPrice.setText("$"+Integer.parseInt(jSpinner1.getValue().toString())*show.getpTicketPrice());
        }

    });
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCancel = new javax.swing.JLabel();
        lblApply = new javax.swing.JLabel();
        lblShowDetail3 = new javax.swing.JLabel();
        lblShowDetail2 = new javax.swing.JLabel();
        lblShowDetail1 = new javax.swing.JLabel();
        lblNum = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        lblCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelMouseClicked(evt);
            }
        });
        getContentPane().add(lblCancel);
        lblCancel.setBounds(670, 10, 100, 50);

        lblApply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblApplyMouseClicked(evt);
            }
        });
        getContentPane().add(lblApply);
        lblApply.setBounds(320, 460, 170, 40);

        lblShowDetail3.setForeground(new java.awt.Color(255, 255, 255));
        lblShowDetail3.setText("price label");
        getContentPane().add(lblShowDetail3);
        lblShowDetail3.setBounds(60, 170, 140, 20);

        lblShowDetail2.setForeground(new java.awt.Color(255, 255, 255));
        lblShowDetail2.setText("Please note you may buy up to maximum of 6 tickets per purchase.");
        getContentPane().add(lblShowDetail2);
        lblShowDetail2.setBounds(60, 150, 560, 16);

        lblShowDetail1.setForeground(new java.awt.Color(255, 255, 255));
        lblShowDetail1.setText("price label");
        getContentPane().add(lblShowDetail1);
        lblShowDetail1.setBounds(60, 130, 410, 16);

        lblNum.setForeground(new java.awt.Color(255, 255, 255));
        lblNum.setText("Number of Tickets");
        getContentPane().add(lblNum);
        lblNum.setBounds(60, 240, 140, 16);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 6, 1));
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(190, 230, 40, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total Price (Before Discount): ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 280, 240, 16);

        lblDiscount.setForeground(new java.awt.Color(255, 255, 255));
        lblDiscount.setVisible(false);
        lblDiscount.setText("lblDiscount");
        getContentPane().add(lblDiscount);
        lblDiscount.setBounds(60, 300, 190, 16);

        lblTotalPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalPrice.setText("jLabel2");
        getContentPane().add(lblTotalPrice);
        lblTotalPrice.setBounds(250, 280, 41, 16);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/Images/ticket_purchase.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelMouseClicked
        // TODO add your handling code here:
        //quit
        dispose();
        iWindow.update();
    }//GEN-LAST:event_lblCancelMouseClicked

    private void lblApplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApplyMouseClicked
        // TODO add your handling code here:
       //Purchase Tickets
       dispose();
       Integer numOfTickets = Integer.parseInt(jSpinner1.getValue().toString());
       ViewShowController.purchaseTickets(show, (Customer) iMuzaMusic.getLoggedUser(), numOfTickets);
       frm.lblSuccess.setText("You have successfully purchased "+numOfTickets+" for show "+show.getpID());
       frm.lblSuccess.setVisible(true);
       frm.refreshShow();
    }//GEN-LAST:event_lblApplyMouseClicked

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblApply;
    private javax.swing.JLabel lblCancel;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblShowDetail1;
    private javax.swing.JLabel lblShowDetail2;
    private javax.swing.JLabel lblShowDetail3;
    private javax.swing.JLabel lblTotalPrice;
    // End of variables declaration//GEN-END:variables
}
