/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Boundary.Rep.Create;

import Boundary.Main.iWindow;
import Controller.Main.iMuzaMusic;
import Entity.EAuth;
import Entity.Rep;

/**
 *
 * @author Administrator
 */
public class createRep extends javax.swing.JInternalFrame {

    /**
     * Creates new form createRep
     */
    public createRep() {
        initComponents();
        lblRepID.setText(Controller.Rep.createManager.getNextID(EAuth.Representative));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblRepID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fldFirstName = new javax.swing.JTextField();
        errFirstName = new javax.swing.JLabel();
        lblerrFirstName = new javax.swing.JLabel();
        xIcon = new javax.swing.JLabel();
        vIcon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fldLastName = new javax.swing.JTextField();
        errLastName = new javax.swing.JLabel();
        lblerrLastName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        errPassword = new javax.swing.JLabel();
        lblerrPassword = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        errSubmit = new javax.swing.JLabel();
        lblerrSubmit = new javax.swing.JLabel();
        fldPassword = new javax.swing.JPasswordField();

        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please use the form below to create a new System Representative");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 11, 490, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Rep ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 80, 14);

        lblRepID.setForeground(new java.awt.Color(255, 255, 255));
        lblRepID.setText("jLabel3");
        getContentPane().add(lblRepID);
        lblRepID.setBounds(110, 50, 150, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 70, 70, 20);

        fldFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fldFirstNameFocusLost(evt);
            }
        });
        getContentPane().add(fldFirstName);
        fldFirstName.setBounds(110, 70, 150, 20);

        errFirstName.setToolTipText("");
        getContentPane().add(errFirstName);
        errFirstName.setBounds(260, 70, 20, 20);

        lblerrFirstName.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lblerrFirstName);
        lblerrFirstName.setBounds(280, 70, 300, 20);

        xIcon.setVisible(false);
        xIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/Images/x.png"))); // NOI18N
        getContentPane().add(xIcon);
        xIcon.setBounds(610, 100, 20, 20);

        vIcon.setVisible(false);
        vIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/Images/v.png"))); // NOI18N
        getContentPane().add(vIcon);
        vIcon.setBounds(610, 80, 20, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 90, 70, 20);

        fldLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fldLastNameFocusLost(evt);
            }
        });
        getContentPane().add(fldLastName);
        fldLastName.setBounds(110, 90, 150, 20);

        errLastName.setToolTipText("");
        getContentPane().add(errLastName);
        errLastName.setBounds(260, 90, 20, 20);

        lblerrLastName.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lblerrLastName);
        lblerrLastName.setBounds(280, 90, 310, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 110, 70, 20);

        errPassword.setToolTipText("");
        getContentPane().add(errPassword);
        errPassword.setBounds(260, 110, 20, 20);

        lblerrPassword.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lblerrPassword);
        lblerrPassword.setBounds(280, 110, 370, 20);

        jButton1.setText("Create Representative");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 150, 240, 23);

        errSubmit.setToolTipText("");
        getContentPane().add(errSubmit);
        errSubmit.setBounds(260, 150, 40, 20);

        lblerrSubmit.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lblerrSubmit);
        lblerrSubmit.setBounds(300, 150, 200, 20);

        fldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fldPasswordFocusLost(evt);
            }
        });
        getContentPane().add(fldPassword);
        fldPassword.setBounds(110, 110, 150, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fldFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fldFirstNameFocusLost
        // TODO add your handling code here:
        if(fldFirstName.getText().length()<2){
            //Name is too short
            errFirstName.setIcon(xIcon.getIcon());
            lblerrFirstName.setText("Name must have more than 1 character");
        } else if(!fldFirstName.getText().matches("[a-zA-Z]+")){
            //Name contains special chars
            errFirstName.setIcon(xIcon.getIcon());
            lblerrFirstName.setText("Name must contain only letters.");
        } else {
            errFirstName.setIcon(vIcon.getIcon());
            lblerrFirstName.setText("");
        }
        iWindow.update();
    }//GEN-LAST:event_fldFirstNameFocusLost

    private void fldLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fldLastNameFocusLost
        // TODO add your handling code here:
           if(fldLastName.getText().length()<2){
            //Name is too short
            errLastName.setIcon(xIcon.getIcon());
            lblerrLastName.setText("Name must have more than 1 character");
        } else if(!fldLastName.getText().matches("[a-zA-Z]+")){
            //Name contains special chars
            errLastName.setIcon(xIcon.getIcon());
            lblerrLastName.setText("Name must contain only letters.");
        } else {
            errLastName.setIcon(vIcon.getIcon());
            lblerrLastName.setText("");
        }
        iWindow.update();
    }//GEN-LAST:event_fldLastNameFocusLost

    private void fldPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fldPasswordFocusLost
        // TODO add your handling code here:
        if(fldPassword.getText().length()<5){
            //Password too short
            errPassword.setIcon(xIcon.getIcon());
            lblerrPassword.setText("Password must more than 4 characters.");
        } else if(fldPassword.getText().matches("[ ]")){
            errPassword.setIcon(xIcon.getIcon());
            lblerrPassword.setText("Password must not have spaces!");
        } else{
            errPassword.setIcon(vIcon.getIcon());
            lblerrPassword.setText("");
        }
        iWindow.update();
    }//GEN-LAST:event_fldPasswordFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(lblerrFirstName.getText().length()>0 ||
                lblerrLastName.getText().length()>0 ||
                    lblerrPassword.getText().length()>0){
            errSubmit.setIcon(xIcon.getIcon());
            lblerrSubmit.setText("Please fix the errors before proceeding.");
        } else{
            iMuzaMusic.Success("Representative #"+lblRepID.getText()+" has been successfully created.");
            Controller.Rep.createManager.create(new Rep(lblRepID.getText(), fldFirstName.getText(), fldLastName.getText(), fldPassword.getText(), EAuth.Representative));
        }
        
        
        
        iWindow.update();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errFirstName;
    private javax.swing.JLabel errLastName;
    private javax.swing.JLabel errPassword;
    private javax.swing.JLabel errSubmit;
    private javax.swing.JTextField fldFirstName;
    private javax.swing.JTextField fldLastName;
    private javax.swing.JPasswordField fldPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblRepID;
    private javax.swing.JLabel lblerrFirstName;
    private javax.swing.JLabel lblerrLastName;
    private javax.swing.JLabel lblerrPassword;
    private javax.swing.JLabel lblerrSubmit;
    private javax.swing.JLabel vIcon;
    private javax.swing.JLabel xIcon;
    // End of variables declaration//GEN-END:variables
}
