/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Boundary.Main;

import Boundary.General.frmViewShows;
import Entity.Artist;
import Controller.Main.XMLManager;
import Controller.Main.iMuzaMusic;
import java.sql.SQLException;
import Entity.EAuth;
import Boundary.Agent.frmCreateShow;
import Boundary.Agent.frmLocationManager;
import Boundary.Agent.frmManageArtists;
import Boundary.Internal.frmViewReport;
import Boundary.Internal.frmWatchArtists;
import java.awt.Color;
import java.awt.Graphics;
import java.sql.ResultSet;

/**
 *
 * @author Administrator
 */
public class MainGui extends javax.swing.JFrame {

    /**
     * Creates new form MainGui
     */
    public MainGui() throws SQLException {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        refreshVars();
        iWindow.setPanel(ContentFrame);
        iWindow.setLblTitle(lblTitle);

    
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblUsernames = new javax.swing.JLabel();
        lblUserType = new javax.swing.JLabel();
        ContentFrame = new javax.swing.JPanel();
        pnlAgent = new javax.swing.JPanel();
        btnManageArtists = new javax.swing.JLabel();
        btnAddShow = new javax.swing.JLabel();
        btnAddShow1 = new javax.swing.JLabel();
        btnAddShow2 = new javax.swing.JLabel();
        pnlRep = new javax.swing.JPanel();
        btnViewReport = new javax.swing.JLabel();
        pnlLRep = new javax.swing.JPanel();
        btnViewReport2 = new javax.swing.JLabel();
        pnlCustomer = new javax.swing.JPanel();
        btnViewReport1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 766));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 204, 204));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("Page Title");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 240, 20));

        lblUsernames.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUsernames.setForeground(new java.awt.Color(255, 255, 255));
        lblUsernames.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsernames.setText("First Name");
        getContentPane().add(lblUsernames, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 200, 30));

        lblUserType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUserType.setForeground(new java.awt.Color(255, 255, 255));
        lblUserType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserType.setText("User Type");
        getContentPane().add(lblUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 170, 30));

        ContentFrame.setBackground(new Color(0,0,0,0));
        ContentFrame.setForeground(new java.awt.Color(255, 51, 102));
        ContentFrame.setAutoscrolls(true);
        ContentFrame.setOpaque(false);
        ContentFrame.setVisible(false);

        javax.swing.GroupLayout ContentFrameLayout = new javax.swing.GroupLayout(ContentFrame);
        ContentFrame.setLayout(ContentFrameLayout);
        ContentFrameLayout.setHorizontalGroup(
            ContentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        ContentFrameLayout.setVerticalGroup(
            ContentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        getContentPane().add(ContentFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 830, 690));

        pnlAgent.setOpaque(false);

        btnManageArtists.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnManageArtists.setForeground(new java.awt.Color(255, 255, 255));
        btnManageArtists.setText("Manage Artists");
        btnManageArtists.setToolTipText("");
        btnManageArtists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManageArtistsMouseClicked(evt);
            }
        });

        btnAddShow.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAddShow.setForeground(new java.awt.Color(255, 255, 255));
        btnAddShow.setText("Add Shows");
        btnAddShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddShowMouseClicked(evt);
            }
        });

        btnAddShow1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAddShow1.setForeground(new java.awt.Color(255, 255, 255));
        btnAddShow1.setText("View Shows");
        btnAddShow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddShow1MouseClicked(evt);
            }
        });

        btnAddShow2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAddShow2.setForeground(new java.awt.Color(255, 255, 255));
        btnAddShow2.setText("Locations Manager");
        btnAddShow2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddShow2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlAgentLayout = new javax.swing.GroupLayout(pnlAgent);
        pnlAgent.setLayout(pnlAgentLayout);
        pnlAgentLayout.setHorizontalGroup(
            pnlAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddShow, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageArtists, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddShow1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddShow2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlAgentLayout.setVerticalGroup(
            pnlAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgentLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnManageArtists, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddShow, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddShow2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddShow1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        getContentPane().add(pnlAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        pnlRep.setOpaque(false);
        pnlRep.setLayout(null);

        btnViewReport.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnViewReport.setForeground(new java.awt.Color(255, 255, 255));
        btnViewReport.setText("View Shows");
        btnViewReport.setToolTipText("");
        btnViewReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewReportMouseClicked(evt);
            }
        });
        pnlRep.add(btnViewReport);
        btnViewReport.setBounds(20, 11, 190, 50);

        getContentPane().add(pnlRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        pnlLRep.setOpaque(false);
        pnlCustomer.setVisible(false);
        pnlLRep.setLayout(null);

        btnViewReport2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnViewReport2.setForeground(new java.awt.Color(255, 255, 255));
        btnViewReport2.setText("View Shows");
        btnViewReport2.setToolTipText("");
        btnViewReport2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewReport2MouseClicked(evt);
            }
        });
        pnlLRep.add(btnViewReport2);
        btnViewReport2.setBounds(0, 0, 0, 0);

        getContentPane().add(pnlLRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        pnlCustomer.setOpaque(false);
        pnlCustomer.setPreferredSize(new java.awt.Dimension(222, 413));
        pnlCustomer.setVisible(false);
        pnlCustomer.setLayout(null);

        btnViewReport1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnViewReport1.setForeground(new java.awt.Color(255, 255, 255));
        btnViewReport1.setText("View Shows");
        btnViewReport1.setToolTipText("");
        btnViewReport1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewReport1MouseClicked(evt);
            }
        });
        pnlCustomer.add(btnViewReport1);
        btnViewReport1.setBounds(20, 20, 190, 50);

        getContentPane().add(pnlCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/Images/muzagui.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 1020, 770));

        btnExit.setText("jButton1");
        btnExit.setEnabled(false);
        btnExit.setFocusPainted(false);
        btnExit.setFocusable(false);
        btnExit.setRequestFocusEnabled(false);
        btnExit.setRolloverEnabled(false);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 160, 40));

        btnLogout.setText("jButton1");
        btnLogout.setEnabled(false);
        btnLogout.setFocusPainted(false);
        btnLogout.setFocusable(false);
        btnLogout.setRequestFocusEnabled(false);
        btnLogout.setRolloverEnabled(false);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 160, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        iMuzaMusic.log("Logging out..");
        iMuzaMusic.setLoggedUser(null);
        dispose();
        setVisible(false);
        iMuzaMusic.log("Successfully logged out");
        
        LoginGui tmp = new LoginGui();
        iMuzaMusic.log("Activating login screen");
        tmp.setVisible(true);
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        iMuzaMusic.log("Quitting MuzaMusic");
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnManageArtistsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageArtistsMouseClicked
        // TODO add your handling code here:
        frmManageArtists add = new frmManageArtists();
        iWindow.openWin(add);
    }//GEN-LAST:event_btnManageArtistsMouseClicked

    private void btnAddShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddShowMouseClicked
        // TODO add your handling code here:
        frmCreateShow add = new frmCreateShow();
        iWindow.openWin(add);
    }//GEN-LAST:event_btnAddShowMouseClicked

    private void btnViewReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewReportMouseClicked
        // TODO add your handling code here:
        iWindow.openWin(new frmViewShows());
    }//GEN-LAST:event_btnViewReportMouseClicked

    private void btnAddShow1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddShow1MouseClicked
        iWindow.openWin(new frmViewShows());
        
    }//GEN-LAST:event_btnAddShow1MouseClicked

    private void btnAddShow2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddShow2MouseClicked

        iWindow.openWin(new frmLocationManager());
    }//GEN-LAST:event_btnAddShow2MouseClicked

    private void btnViewReport1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewReport1MouseClicked
        // TODO add your handling code here:
        iWindow.openWin(new frmViewShows());
    }//GEN-LAST:event_btnViewReport1MouseClicked

    private void btnViewReport2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewReport2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewReport2MouseClicked


    public void refreshVars() {
        lblTitle.setText("Homepage");
        lblUserType.setText("" + iMuzaMusic.getLoggedUser().getUserAuth());
        lblUsernames.setText(iMuzaMusic.getLoggedUser().getFirstName() + " " + iMuzaMusic.getLoggedUser().getLastName());
        pnlAgent.setVisible(false);
        pnlRep.setVisible(false);
        switch (iMuzaMusic.getLoggedUser().getUserAuth()) {
            case Agent:
                pnlAgent.setVisible(true);
            case Representative:
                pnlRep.setVisible(true);
            case Location_Representative:
                pnlLRep.setVisible(true);
            case Customer:
                pnlCustomer.setVisible(true);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentFrame;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnAddShow;
    private javax.swing.JLabel btnAddShow1;
    private javax.swing.JLabel btnAddShow2;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel btnManageArtists;
    private javax.swing.JLabel btnViewReport;
    private javax.swing.JLabel btnViewReport1;
    private javax.swing.JLabel btnViewReport2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserType;
    private javax.swing.JLabel lblUsernames;
    private javax.swing.JPanel pnlAgent;
    private javax.swing.JPanel pnlCustomer;
    private javax.swing.JPanel pnlLRep;
    private javax.swing.JPanel pnlRep;
    // End of variables declaration//GEN-END:variables

}
