/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Boundary.Internal.Agent;

/**
 *
 * @author nisan
 */
public class frmEvaluateArtist extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public frmEvaluateArtist() {
        setUndecorated(true);
        setLocationRelativeTo(null);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EvaluatedScrollPane1 = new javax.swing.JScrollPane();
        EvaluatedJList1 = new javax.swing.JList<>();
        unEvaluatedScrollPane = new javax.swing.JScrollPane();
        unEvaluatedJList = new javax.swing.JList<>();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        EvaluatedJList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        unEvaluatedJList.removeAll();
        EvaluatedScrollPane1.setViewportView(EvaluatedJList1);

        getContentPane().add(EvaluatedScrollPane1);
        EvaluatedScrollPane1.setBounds(570, 160, 140, 146);

        unEvaluatedJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        unEvaluatedJList.removeAll();
        unEvaluatedScrollPane.setViewportView(unEvaluatedJList);

        getContentPane().add(unEvaluatedScrollPane);
        unEvaluatedScrollPane.setBounds(120, 160, 140, 146);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/Images/artist_evaluations.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, -80, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEvaluateArtist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEvaluateArtist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEvaluateArtist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEvaluateArtist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEvaluateArtist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> EvaluatedJList1;
    private javax.swing.JScrollPane EvaluatedScrollPane1;
    private javax.swing.JLabel bg;
    private javax.swing.JList<String> unEvaluatedJList;
    private javax.swing.JScrollPane unEvaluatedScrollPane;
    // End of variables declaration//GEN-END:variables
}
