/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Boundary.Internal.Agent;


import Boundary.Main.iWindow;
import Controller.Agent.LocationsController;
import Controller.General.iMuzaMusic;
import Entity.Location;
import Entity.OpenLocation;
import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Graphics;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author nisan
 */
public class frmLocationManager extends javax.swing.JInternalFrame {
    Location formLocation = null;
    /**
     * Creates new form frmLocationManager
     */
    public frmLocationManager() {
        setTitle("Location Management");
        initComponents();
        LocationsController.updateFormData(slctLocation, jTable1);
         jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent event) {
                    // do some actions here, for example
                    // print first column value from selected row
                    try{
                        System.out.println(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
                        formLocation = (Location) jTable1.getValueAt(jTable1.getSelectedRow(), 1);
                        
                        updateData();
                    }
                    catch(Exception e){
                        
                    }
                }
            });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        slctLocation = new javax.swing.JComboBox<>();
        btnFavorite = new javax.swing.JButton();
        pnlLocationDetails = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPhoneNum = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblMaxCapacity = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlOpenLocationDetails = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblStageTop = new javax.swing.JLabel();
        lblExistingSits = new javax.swing.JLabel();
        lblStageLifted = new javax.swing.JLabel();
        lblExistingAmp = new javax.swing.JLabel();
        lblExistingToilets = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            @Override
            public Class getColumnClass(int column) {
                switch (column) {
                    case 0:
                    return String.class;
                    case 1:
                    return String.class;
                    case 2:
                    return String.class;
                    case 3:
                    return String.class;
                    default:
                    return Boolean.class;
                }
            }
        };
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        vIcon = new javax.swing.JLabel();
        xIcon = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to Location Management.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(43, 25, 340, 20);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Please use the below form to favorite new locations, or unfavorite locations you already favorited.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(43, 48, 574, 16);

        slctLocation.setModel(new javax.swing.DefaultComboBoxModel<>());
        slctLocation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                slctLocationItemStateChanged(evt);
            }
        });
        getContentPane().add(slctLocation);
        slctLocation.setBounds(40, 100, 200, 22);

        btnFavorite.setText("Favorite");
        btnFavorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoriteActionPerformed(evt);
            }
        });
        getContentPane().add(btnFavorite);
        btnFavorite.setBounds(260, 95, 79, 30);

        pnlLocationDetails.setVisible(false);
        pnlLocationDetails.setOpaque(false);
        pnlLocationDetails.setLayout(null);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Max Capacity:");
        pnlLocationDetails.add(jLabel3);
        jLabel3.setBounds(10, 90, 110, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Location Name:");
        pnlLocationDetails.add(jLabel4);
        jLabel4.setBounds(10, 10, 110, 16);

        lblPhoneNum.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNum.setText("jLabel5");
        pnlLocationDetails.add(lblPhoneNum);
        lblPhoneNum.setBounds(160, 70, 300, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Location Address: ");
        pnlLocationDetails.add(jLabel5);
        jLabel5.setBounds(10, 30, 110, 16);

        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("jLabel5");
        pnlLocationDetails.add(lblName);
        lblName.setBounds(160, 10, 220, 20);

        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText("jLabel5");
        pnlLocationDetails.add(lblAddress);
        lblAddress.setBounds(160, 30, 260, 20);

        lblContact.setForeground(new java.awt.Color(255, 255, 255));
        lblContact.setText("jLabel5");
        pnlLocationDetails.add(lblContact);
        lblContact.setBounds(160, 50, 220, 20);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Location Contact: ");
        pnlLocationDetails.add(jLabel6);
        jLabel6.setBounds(10, 50, 110, 16);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Location Phone:");
        pnlLocationDetails.add(jLabel7);
        jLabel7.setBounds(10, 70, 110, 16);

        lblMaxCapacity.setForeground(new java.awt.Color(255, 255, 255));
        lblMaxCapacity.setText("jLabel5");
        pnlLocationDetails.add(lblMaxCapacity);
        lblMaxCapacity.setBounds(160, 90, 320, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/Images/mapsIcon.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        pnlLocationDetails.add(jLabel8);
        jLabel8.setBounds(440, 30, 70, 60);

        pnlOpenLocationDetails.setOpaque(false);
        pnlOpenLocationDetails.setLayout(null);
        pnlOpenLocationDetails.setVisible(false);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Stage Top: ");
        pnlOpenLocationDetails.add(jLabel11);
        jLabel11.setBounds(10, 10, 85, 16);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Existing Sits: ");
        pnlOpenLocationDetails.add(jLabel12);
        jLabel12.setBounds(10, 30, 85, 16);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Stage Lifted: ");
        pnlOpenLocationDetails.add(jLabel13);
        jLabel13.setBounds(10, 50, 85, 16);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Existing Amplifiers: ");
        pnlOpenLocationDetails.add(jLabel14);
        jLabel14.setBounds(10, 70, 113, 16);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Including toilets: ");
        pnlOpenLocationDetails.add(jLabel15);
        jLabel15.setBounds(10, 90, 98, 16);

        lblStageTop.setForeground(new java.awt.Color(255, 255, 255));
        lblStageTop.setText(" ");
        pnlOpenLocationDetails.add(lblStageTop);
        lblStageTop.setBounds(160, 10, 78, 16);

        lblExistingSits.setForeground(new java.awt.Color(255, 255, 255));
        lblExistingSits.setText(" ");
        pnlOpenLocationDetails.add(lblExistingSits);
        lblExistingSits.setBounds(160, 30, 95, 16);

        lblStageLifted.setForeground(new java.awt.Color(255, 255, 255));
        lblStageLifted.setText(" ");
        pnlOpenLocationDetails.add(lblStageLifted);
        lblStageLifted.setBounds(160, 50, 95, 16);

        lblExistingAmp.setForeground(new java.awt.Color(255, 255, 255));
        pnlOpenLocationDetails.add(lblExistingAmp);
        lblExistingAmp.setBounds(160, 70, 95, 20);

        lblExistingToilets.setForeground(new java.awt.Color(255, 255, 255));
        lblExistingToilets.setText(" ");
        pnlOpenLocationDetails.add(lblExistingToilets);
        lblExistingToilets.setBounds(160, 90, 114, 20);

        pnlLocationDetails.add(pnlOpenLocationDetails);
        pnlOpenLocationDetails.setBounds(0, 100, 510, 130);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Launch Google Maps");
        pnlLocationDetails.add(jLabel16);
        jLabel16.setBounds(410, 10, 180, 16);

        getContentPane().add(pnlLocationDetails);
        pnlLocationDetails.setBounds(40, 130, 560, 260);

        jTable1.setBackground(new Color(0,0,0,0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 400, 510, 160);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Your favorited places");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 380, 210, 16);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("[Apply Changes]");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jLabel9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel9KeyReleased(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(470, 380, 120, 20);

        vIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/Images/v.png"))); // NOI18N
        vIcon.setVisible(false);
        getContentPane().add(vIcon);
        vIcon.setBounds(750, 340, 48, 16);

        xIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/Images/x.png"))); // NOI18N
        xIcon.setVisible(false);
        getContentPane().add(xIcon);
        xIcon.setBounds(750, 320, 16, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        iMuzaMusic.OpenURI(formLocation.getUrlGoogleMaps());
    }//GEN-LAST:event_jLabel8MouseClicked

    private void slctLocationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_slctLocationItemStateChanged
        // TODO add your handling code here:
        Location loc = (Location) slctLocation.getSelectedItem();
        if(loc==null || loc.equals(new Location("0000"))){
            pnlLocationDetails.setVisible(false);
            formLocation = null;
            return;
        }
        formLocation = loc;
        updateData();
    }//GEN-LAST:event_slctLocationItemStateChanged

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        for(int i=0; i<jTable1.getRowCount(); i++){
            String LocationID = (String) jTable1.getValueAt(i, 0);
            Boolean status = (Boolean) jTable1.getValueAt(i, 2);


            if(status){
                LocationsController.unfavLocation(LocationID);
                
                iMuzaMusic.log("Cancel favorited location: LocationID: "+LocationID);

            }

        }
        LocationsController.updateFormData(slctLocation, jTable1);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel9KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9KeyReleased

    private void btnFavoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoriteActionPerformed
        if(formLocation!=null && !slctLocation.getSelectedItem().equals(new Location("0000"))){
        LocationsController.addFav(formLocation.getLocationID());
        LocationsController.updateFormData(slctLocation, jTable1);
        }
        
        
        
    }//GEN-LAST:event_btnFavoriteActionPerformed

    public void updateData(){
        pnlLocationDetails.setVisible(true);
        lblName.setText(formLocation.getStrName());
        lblAddress.setText(formLocation.getStrAddress());
        lblContact.setText(formLocation.getStrEmail());
        lblPhoneNum.setText("0"+formLocation.getiPhoneNum());
        lblMaxCapacity.setText(""+formLocation.getMaxCapacity());
        
        if(formLocation instanceof OpenLocation){
            OpenLocation tmp = (OpenLocation) formLocation;
            pnlOpenLocationDetails.setVisible(true);
            lblExistingAmp.setIcon(getIcon(tmp.getIsExistingAmp()));
            lblExistingSits.setIcon(getIcon(tmp.getIsExistingSits()));
            lblExistingToilets.setIcon(getIcon(tmp.getIsExistingToilets()));
            lblStageLifted.setIcon(getIcon(tmp.getIsStageLifted()));
            lblStageTop.setText(tmp.getStageTop());
            
        } else pnlOpenLocationDetails.setVisible(false);
        
        
        iWindow.update();
    }
        
    public Icon getIcon(Boolean status){
        if(status)
            return vIcon.getIcon();
        return xIcon.getIcon();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFavorite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblExistingAmp;
    private javax.swing.JLabel lblExistingSits;
    private javax.swing.JLabel lblExistingToilets;
    private javax.swing.JLabel lblMaxCapacity;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoneNum;
    private javax.swing.JLabel lblStageLifted;
    private javax.swing.JLabel lblStageTop;
    private javax.swing.JPanel pnlLocationDetails;
    private javax.swing.JPanel pnlOpenLocationDetails;
    private javax.swing.JComboBox<Entity.Location> slctLocation;
    private javax.swing.JLabel vIcon;
    private javax.swing.JLabel xIcon;
    // End of variables declaration//GEN-END:variables
}
