/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Boundary.Customer;

import Boundary.Main.iWindow;
import Controller.Main.iMuzaMusic;
import Entity.Customer;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.ImageObserver;
import java.awt.image.ImageProducer;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.nio.file.Files;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Administrator
 */
public class frmViewBDayCard extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmViewBDayCard
     */
    public frmViewBDayCard(){
        initComponents();
        if(Controller.Customer.BDayController.canDisplay((Customer)iMuzaMusic.getLoggedUser()))
            displayBDay.setVisible(true);
        else {
            displayErr.setVisible(true);
            return;
        }
        lblTitle.setText("Happy Birthday "+iMuzaMusic.getLoggedUser().getFirstName()+"!");
        txtLetter.setText(Controller.Customer.BDayController.getBirthdayText((Customer)iMuzaMusic.getLoggedUser()));
        jScrollPane2.getViewport().setOpaque(false);
        jScrollPane2.getViewport().setBorder(null);
        txtLetter.setEnabled(false);
        txtLetter.setEditable(false);
        txtLetter.setFocusable(false);
        iWindow.update();
        //Get text
        List<File> sigList = Controller.Customer.BDayController.getSigList((Customer)iMuzaMusic.getLoggedUser());
        
        for(File f : sigList){
            //Artist sigs
            
            JLabel lbl = new JLabel();
            lbl.setIcon(Controller.Main.FileManager.fileToIcon(f));
            
            lbl.setSize(new Dimension(150, 70));
            lbl.setMaximumSize(new Dimension(150, 70));
            lbl.setMinimumSize(new Dimension(150, 70));
            lbl.setBorder(jScrollPane2.getBorder());
            
            try {
                lbl.setIcon(new ImageIcon(new ImageIcon(f.toURL()).getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_DEFAULT)));
            } catch (MalformedURLException ex) {
                Logger.getLogger(frmViewBDayCard.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            sigPanel.add(lbl);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayBDay = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLetter = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        sigPanel = new javax.swing.JPanel();
        displayErr = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        displayBDay.setOpaque(false);
        displayBDay.setLayout(null);
        displayBDay.setVisible(false);

        jScrollPane2.setBorder(null);
        jScrollPane2.setOpaque(false);

        txtLetter.setEditable(false);
        txtLetter.setBorder(null);
        txtLetter.setForeground(new java.awt.Color(255, 255, 255));
        txtLetter.setOpaque(false);
        jScrollPane2.setViewportView(txtLetter);

        displayBDay.add(jScrollPane2);
        jScrollPane2.setBounds(170, 110, 610, 200);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boundary/Images/balloons.png"))); // NOI18N
        displayBDay.add(jLabel2);
        jLabel2.setBounds(20, -20, 160, 300);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Happy Birthday ");
        displayBDay.add(lblTitle);
        lblTitle.setBounds(160, 40, 530, 70);

        sigPanel.setOpaque(false);
        displayBDay.add(sigPanel);
        sigPanel.setBounds(10, 290, 710, 270);

        getContentPane().add(displayBDay);
        displayBDay.setBounds(10, 10, 1040, 570);

        displayErr.setOpaque(false);
        displayErr.setLayout(null);
        displayErr.setVisible(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Your Birthday Card cannot be generated because you do not fan an artist yet.");
        displayErr.add(jLabel1);
        jLabel1.setBounds(50, 30, 870, 16);

        jButton1.setText("Fan Artists");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        displayErr.add(jButton1);
        jButton1.setBounds(50, 70, 200, 25);

        getContentPane().add(displayErr);
        displayErr.setBounds(0, 0, 1040, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        iWindow.openWin(new frmFanArtist());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayBDay;
    private javax.swing.JPanel displayErr;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel sigPanel;
    private javax.swing.JTextPane txtLetter;
    // End of variables declaration//GEN-END:variables
}
